/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:6ab964ea-8cc6-4e87-9c86-395932260b1d",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_Q5BTJJSXU",
    "aws_user_pools_web_client_id": "4n4lq6795nt9lc7bfatofmm5pg",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "wttj-datascience-junglelabs712a5-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};

export default awsmobile;

